name: test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup clojure
      uses: DeLaGuardo/setup-clojure@master
      with:
        cli: 1.11.1.1149
    - name: run bearsql unit tests
      run: clojure -A:dev:test
